#!/bin/bash

set -e

PREFIX="> pre-commit [$(basename $0)]\t\t"
MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xms768M"
GREP_OPTIONS=

echo -e  "$PREFIX auto-applying spotless changes"
mvn -T 1C -q spotless:apply 
git add -u


